package com.medrep.app.model;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

/**
 * TArea generated by hbm2java
 */
public class TransformModel implements java.io.Serializable {

	private Integer transformId;
	private String title;
	private String tagDesc;
	private String transformDesc;
	private Integer sourceId;
	private String sourceName;
	private Integer categoryId;
	private String categoryName;
	private Integer therapeuticId;
	private String therapeuticName;
	private String postUrl;
	private String coverImgUrl;
	private String innerImgUrl;
	private String videoUrl;
	private Integer userId;
	private String createdOn;
	private int contentType;
	private String subCategory;

	private MultipartFile coverImgFile;
	private MultipartFile innerImgFile;
	private MultipartFile videoFile;


	/**
	 * @return the transformId
	 */
	public Integer getTransformId() {
		return transformId;
	}
	/**
	 * @param transformId the transformId to set
	 */
	public void setTransformId(Integer transformId) {
		this.transformId = transformId;
	}
	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}
	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	/**
	 * @return the tagDesc
	 */
	public String getTagDesc() {
		return tagDesc;
	}
	/**
	 * @param tagDesc the tagDesc to set
	 */
	public void setTagDesc(String tagDesc) {
		this.tagDesc = tagDesc;
	}

	/**
	 * @return the sourceId
	 */
	public Integer getSourceId() {
		return sourceId;
	}
	/**
	 * @param sourceId the sourceId to set
	 */
	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}
	/**
	 * @return the sourceName
	 */
	public String getSourceName() {
		return sourceName;
	}
	/**
	 * @param sourceName the sourceName to set
	 */
	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}
	/**
	 * @return the categoryId
	 */
	public Integer getCategoryId() {
		return categoryId;
	}
	/**
	 * @param categoryId the categoryId to set
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}
	/**
	 * @return the categoryName
	 */
	public String getCategoryName() {
		return categoryName;
	}
	/**
	 * @param categoryName the categoryName to set
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
	/**
	 * @return the therapeuticId
	 */
	public Integer getTherapeuticId() {
		return therapeuticId;
	}
	/**
	 * @param therapeuticId the therapeuticId to set
	 */
	public void setTherapeuticId(Integer therapeuticId) {
		this.therapeuticId = therapeuticId;
	}
	/**
	 * @return the postUrl
	 */
	public String getPostUrl() {
		return postUrl;
	}
	/**
	 * @param postUrl the postUrl to set
	 */
	public void setPostUrl(String postUrl) {
		this.postUrl = postUrl;
	}
	/**
	 * @return the coverImgUrl
	 */
	public String getCoverImgUrl() {
		return coverImgUrl;
	}
	/**
	 * @param coverImgUrl the coverImgUrl to set
	 */
	public void setCoverImgUrl(String coverImgUrl) {
		this.coverImgUrl = coverImgUrl;
	}
	/**
	 * @return the innerImgUrl
	 */
	public String getInnerImgUrl() {
		return innerImgUrl;
	}
	/**
	 * @param innerImgUrl the innerImgUrl to set
	 */
	public void setInnerImgUrl(String innerImgUrl) {
		this.innerImgUrl = innerImgUrl;
	}
	/**
	 * @return the videoUrl
	 */
	public String getVideoUrl() {
		return videoUrl;
	}
	/**
	 * @param videoUrl the videoUrl to set
	 */
	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}
	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}
	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	/**
	 * @return the createdOn
	 */
	public String getCreatedOn() {
		return createdOn;
	}
	/**
	 * @return the coverImgFile
	 */
	public MultipartFile getCoverImgFile() {
		return coverImgFile;
	}
	/**
	 * @param coverImgFile the coverImgFile to set
	 */
	public void setCoverImgFile(MultipartFile coverImgFile) {
		this.coverImgFile = coverImgFile;
	}
	/**
	 * @return the innerImgFile
	 */
	public MultipartFile getInnerImgFile() {
		return innerImgFile;
	}
	/**
	 * @param innerImgFile the innerImgFile to set
	 */
	public void setInnerImgFile(MultipartFile innerImgFile) {
		this.innerImgFile = innerImgFile;
	}
	/**
	 * @return the videoFile
	 */
	public MultipartFile getVideoFile() {
		return videoFile;
	}
	/**
	 * @param videoFile the videoFile to set
	 */
	public void setVideoFile(MultipartFile videoFile) {
		this.videoFile = videoFile;
	}
	/**
	 * @param createdOn the createdOn to set
	 */
	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}
	/**
	 * @return the transformDesc
	 */
	public String getTransformDesc() {
		return transformDesc;
	}
	/**
	 * @param transformDesc the transformDesc to set
	 */
	public void setTransformDesc(String transformDesc) {
		this.transformDesc = transformDesc;
	}
	/**
	 * @return the therapeuticName
	 */
	public String getTherapeuticName() {
		return therapeuticName;
	}
	/**
	 * @param therapeuticName the therapeuticName to set
	 */
	public void setTherapeuticName(String therapeuticName) {
		this.therapeuticName = therapeuticName;
	}

	public int getContentType() {
		return contentType;
	}
	public void setContentType(int contentType) {
		this.contentType = contentType;
	}
	public String getSubCategory() {
		return subCategory;
	}
	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}
}