package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TArea generated by hbm2java
 */
@Entity
@Table(name = "T_ACTIVITY", uniqueConstraints = @UniqueConstraint(columnNames = "ACTIVITY_ID") )
public class ActivityEntity implements java.io.Serializable {

	

	private Integer activityId;
	private String userType;
	private String activityType;
	private String activityStatus;
	private Date lastUpdateDateTime;
	private Integer userId;
	private Integer activityTypeId;
	private Integer companyId;
	
	
	public ActivityEntity() {
	}
	
	public ActivityEntity(Integer activityId, String userType, String activityType, String activityStatus,
			Date lastUpdateDateTime, Integer userId, Integer activityTypeId) {
		super();
		this.activityId = activityId;
		this.userType = userType;
		this.activityType = activityType;
		this.activityStatus = activityStatus;
		this.lastUpdateDateTime = lastUpdateDateTime;
		this.userId = userId;
		this.activityTypeId = activityTypeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACTIVITY_ID", nullable = false)
	public Integer getActivityId() {
		return activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	@Column(name = "ACTIVITY_TYPE")
	public String getActivityType() {
		return activityType;
	}

	public void setActivityType(String activityType) {
		this.activityType = activityType;
	}
	
	@Column(name = "ACTIVITY_STATUS")
	public String getActivityStatus() {
		return activityStatus;
	}
	

	public void setActivityStatus(String activityStatus) {
		this.activityStatus = activityStatus;
	}
	
	@Column(name = "UPDATE_DATE")
	public Date getLastUpdateDateTime() {
		return lastUpdateDateTime;
	}

	public void setLastUpdateDateTime(Date lastUpdateDateTime) {
		this.lastUpdateDateTime = lastUpdateDateTime;
	}
	
	@Column(name = "USER_ID")
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	@Column(name = "ACTIVITY_TYPE_ID")
	public Integer getActivityTypeId() {
		return activityTypeId;
	}

	public void setActivityTypeId(Integer activityTypeId) {
		this.activityTypeId = activityTypeId;
	}
	
	@Column(name = "USER_TYPE", length=10)
	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "COMPANY_ID")
	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	

}
