package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TArea generated by hbm2java
 */
@Entity
@Table(name = "T_AREA", uniqueConstraints = @UniqueConstraint(columnNames = "ZONE_ID") )
public class AreaEntity implements java.io.Serializable {

	private Integer areaId;
	private String areaName;
	private String areaDesc;
	private Integer companyId;
	private Integer zoneId;
	private Integer areaOwner;

	public AreaEntity() {
	}

	public AreaEntity(String areaName, String areaDesc, Integer companyId, Integer zoneId, Integer areaOwner) {
		this.areaName = areaName;
		this.areaDesc = areaDesc;
		this.companyId = companyId;
		this.zoneId = zoneId;
		this.areaOwner = areaOwner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AREA_ID", nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "AREA_NAME")
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "AREA_DESC")
	public String getAreaDesc() {
		return this.areaDesc;
	}

	public void setAreaDesc(String areaDesc) {
		this.areaDesc = areaDesc;
	}

	@Column(name = "COMPANY_ID")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "ZONE_ID", unique = true)
	public Integer getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	@Column(name = "AREA_OWNER")
	public Integer getAreaOwner() {
		return this.areaOwner;
	}

	public void setAreaOwner(Integer areaOwner) {
		this.areaOwner = areaOwner;
	}

}
