package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TCompany generated by hbm2java
 */
@Entity
@Table(name = "T_COMPANY")
public class CompanyEntity implements java.io.Serializable {

	private Integer companyId;
	private String companyName;
	private String companyDesc;
	private String contactName;
	private String contactNo;
	private Integer locationId;
	private Integer dpId;
	private String companyUrl;
	private String status;
	private Set<TherapeuticAreaEntity> therapeuticAreaEntities = new HashSet<TherapeuticAreaEntity>();
	/*private DisplayPictureEntity displayPicture;
	private LocationEntity location;*/

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COMPANY_ID", nullable = false)
	public Integer getCompanyId() {
		return this.companyId;
	}
	@Column(name = "COMPANY_NAME")
	public String getCompanyName() {
		return this.companyName;
	}


	@Column(name = "COMPANY_DESC")
	public String getCompanyDesc() {
		return this.companyDesc;
	}

	@Column(name = "CONTACT_NAME")
	public String getContactName() {
		return contactName;
	}

	@Column(name = "LOCATION_ID")
	public Integer getLocationId() {
		return this.locationId;
	}

	@Column(name = "CONTACT_NO")
	public String getContactNo() {
		return contactNo;
	}

	@Column(name = "DP_ID")
	public Integer getDpId() {
		return this.dpId;
	}

	@Column(name = "COMPANY_URL")
	public String getCompanyUrl() {
		return companyUrl;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	@ManyToMany(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
	@JoinTable(
            name = "T_PHARMA_THERAPEUTICS",
            joinColumns = @JoinColumn(name = "COMPANY_ID"),
            inverseJoinColumns = @JoinColumn(name = "THERAPEUTIC_ID")
    )
	public Set<TherapeuticAreaEntity> getTherapeuticAreaEntities() {
		return therapeuticAreaEntities;
	}

	public CompanyEntity() {
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public CompanyEntity(String companyName, String companyDesc, Integer locationId) {
		this.companyName = companyName;
		this.companyDesc = companyDesc;
		this.locationId  = locationId;
	}

	public void setDpId(Integer dpId) {
		this.dpId = dpId;
	}

	public void setTherapeuticAreaEntities(Set<TherapeuticAreaEntity> therapeuticAreaEntities) {
		this.therapeuticAreaEntities = therapeuticAreaEntities;
	}

	public void setContactNo(String contcatNo) {
		this.contactNo = contcatNo;
	}
	public void setContactName(String contactName) {
		this.contactName = contactName;
	}
	public void setStatus(String status) {
		this.status = status;
	}

	public void setCompanyUrl(String companyUrl) {
		this.companyUrl = companyUrl;
	}

	public void setCompanyDesc(String companyDesc) {
		this.companyDesc = companyDesc;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
