package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TDisplayPicture generated by hbm2java
 */
@Entity
@Table(name = "T_DISPLAY_PICTURE")
public class DisplayPictureEntity implements java.io.Serializable {

	private Integer dpId;
	private String imageUrl;

	public DisplayPictureEntity() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DP_ID", nullable = false)
	public Integer getDpId() {
		return this.dpId;
	}

	public void setDpId(Integer dpId) {
		this.dpId = dpId;
	}


	@Column(name="IMAGE_URL")
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
