package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDoctorAppointment generated by hbm2java
 */
@Entity
@Table(name = "T_DOCTOR_APPOINTMENT")
public class DoctorAppointmentEntity implements java.io.Serializable {

	private Integer appointmentId;
	private String title;
	private String appointmentDesc;
	private Integer doctorId;
	private Integer pharmaRepId;


	private Integer notificationId;
	private Date startDate;
	private Integer duration;
	private String feedback;
	private String status;
	private Date createdOn;
	private String location;

	private String remindMe;
	private Date reminderTime;
	public DoctorAppointmentEntity() {
	}

	public DoctorAppointmentEntity(String title, String appointmentDesc, Integer doctorId, Integer notificationId,
			Date startDate, Integer duration, String feedback, String status, Date createdOn) {
		this.title = title;
		this.appointmentDesc = appointmentDesc;
		this.doctorId = doctorId;
		this.notificationId = notificationId;
		this.startDate = startDate;
		this.duration = duration;
		this.feedback = feedback;
		this.status = status;
		this.createdOn = createdOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "APPOINTMENT_ID", nullable = false)
	public Integer getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "APPOINTMENT_DESC", length = 500)
	public String getAppointmentDesc() {
		return this.appointmentDesc;
	}

	public void setAppointmentDesc(String appointmentDesc) {
		this.appointmentDesc = appointmentDesc;
	}

	@Column(name = "DOCTOR_ID")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "PHARMAREP_ID")
	public Integer getPharmaRepId() {
		return pharmaRepId;
	}

	public void setPharmaRepId(Integer pharmaRepId) {
		this.pharmaRepId = pharmaRepId;
	}

	@Column(name = "NOTIFICATION_ID")
	public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}


	@Column(name = "DURATION")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "FEEDBACK")
	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_ON", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "LOCATION")
	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name="REMIND_ME")
	public String getRemindMe() {
		return remindMe;
	}
	public void setRemindMe(String remindMe) {
		this.remindMe = remindMe;
	}

	@Column(name="REMINDER_TIME")
	public Date getReminderTime() {
		return reminderTime;
	}
	public void setReminderTime(Date reminderTime) {
		this.reminderTime = reminderTime;
	}

	@Override
	public String toString() {
		return "DoctorAppointmentEntity [doctorId=" + doctorId + ", remindMe=" + remindMe + ", reminderTime="
				+ reminderTime + ",appointmentId="+appointmentId+",repId="+pharmaRepId+"]";
	}


}
