package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDoctorSurvey generated by hbm2java
 */
@Entity
@Table(name = "T_DOCTOR_SURVEY", uniqueConstraints = { @UniqueConstraint(columnNames = "DOCTOR_ID"),
		@UniqueConstraint(columnNames = "SURVEY_ID") })
public class DoctorSurveyEntity implements java.io.Serializable {

	private int doctorSurveyId;
	private Integer doctorId;
	private String status;
	private Date createdOn;
	private Date updatedOn;
	private String createdBy;
	private String updatedBy;
	private String  refId;
	private String reminderSent;
	private Date reminderSentOn;
	private SurveyEntity survey;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DOCTOR_SURVEY_ID", nullable = false)
	public int getDoctorSurveyId() {
		return this.doctorSurveyId;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
    @JoinColumn(name="SURVEY_ID",nullable=false,unique=false)
	public SurveyEntity getSurvey() {
		return survey;
	}

	@Column(name = "DOCTOR_ID", unique = true)
	public Integer getDoctorId() {
		return this.doctorId;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return this.status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_ON",length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public String getCreatedBy() {
		return createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_ON",length = 19)
	public Date getUpdatedOn() {
		return updatedOn;
	}

	@Column(name = "UPDATED_BY", nullable = false)
	public String getUpdatedBy() {
		return updatedBy;
	}

	@Column(name = "REF_ID")
	public String getRefId() {
		return refId;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}


	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public void setDoctorSurveyId(int doctorSurveyId) {
		this.doctorSurveyId = doctorSurveyId;
	}
	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public void setSurvey(SurveyEntity survey) {
		this.survey = survey;
	}

	public DoctorSurveyEntity() {
	}

	public DoctorSurveyEntity(int doctorSurveyId) {
		this.doctorSurveyId = doctorSurveyId;
	}

	public DoctorSurveyEntity(int doctorSurveyId, Integer doctorId, String status, Date createdOn) {
		this.doctorSurveyId = doctorSurveyId;
		this.doctorId = doctorId;
		this.status = status;
		this.createdOn = createdOn;
	}


	@Column(name = "REMINDER_SENT")
	public String getReminderSent() {
		return reminderSent;
	}

	public void setReminderSent(String reminderSent) {
		this.reminderSent = reminderSent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REMINDER_SENT_ON",length = 19)
	public Date getReminderSentOn() {
		return reminderSentOn;
	}

	public void setReminderSentOn(Date reminderSentOn) {
		this.reminderSentOn = reminderSentOn;
	}
}
