package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.json.simple.JSONArray;

/**
 * TDoctor generated by hbm2java
 */
@Entity
@Table(name = "T_DOCTOR", uniqueConstraints = @UniqueConstraint(columnNames = "USER_ID") )
public class DoctorEntity implements java.io.Serializable {

	private Integer doctorId;
	private UserEntity user;
	private String registrationYear;
	private String registrationNumber;
	private String stateMedCouncil;
	private String therapeuticId;
	private String qualification;
	private String status;
	private Integer workExpYears;
	private Integer workExpMonths;
	

	

	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public DoctorEntity() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DOCTOR_ID", nullable = false)
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID",nullable=false,unique=true)
	public UserEntity getUser() {
		return this.user;
	}

	public void setUser(UserEntity user) {
		this.user = user;
	}

	@Column(name = "REGISTRATION_YEAR")
	public String getRegistrationYear() {
		return this.registrationYear;
	}

	public void setRegistrationYear(String registrationYear) {
		this.registrationYear = registrationYear;
	}

	@Column(name = "REGISTRATION_NUMBER")
	public String getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}
	@Column(name = "WORK_EXP_YEARS")
	public Integer getWorkExpYears() {
		return workExpYears;
	}

	public void setWorkExpYears(Integer workExpYears) {
		this.workExpYears = workExpYears;
	}

	
	@Column(name = "WORK_EXP_MONTHS")
	public Integer getWorkExpMonths() {
		return workExpMonths;
	}

	public void setWorkExpMonths(Integer workExpMonths) {
		this.workExpMonths = workExpMonths;
	}
	
	@Column(name = "STATE_MED_COUNCIL")
	public String getStateMedCouncil() {
		return this.stateMedCouncil;
	}

	public void setStateMedCouncil(String stateMedCouncil) {
		this.stateMedCouncil = stateMedCouncil;
	}

	@Column(name = "THERAPEUTIC_ID")
	public String getTherapeuticId() {
		return this.therapeuticId;
	}

	public void setTherapeuticId(String therapeuticId) {
		this.therapeuticId = therapeuticId;
	}

	@Column(name = "QUALIFICATION")
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

}
