package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDoctorNotification generated by hbm2java
 */
@Entity
@Table(name = "P_DOCTOR_CONSULTINGS", uniqueConstraints = { @UniqueConstraint(columnNames = "DOCTOR_ID") })
public class DoctorConsultingsEntity implements java.io.Serializable {

	private Integer consultingsId;
	private Integer doctorId;
	private String consultingsType;
	private Integer addressId;
	private String contactNumber;
	private Integer maxAppointments;
	private Integer fee;
	private String consultingsFrom;
	private String consultingsTo;
	private String consultingsDays;
	private String responsetimefrom;
	private String  responsetimeto;

	private String address1;
	private String address2;
	private String locatity;
	private String city;
	private String state;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CONSULTING_ID", nullable = false)
	public Integer getConsultingsId() {
		return consultingsId;
	}
	public void setConsultingsId(Integer consultingsId) {
		this.consultingsId = consultingsId;
	}
	
	@Column(name = "DOCTOR_ID")
	public Integer getDoctorId() {
		return doctorId;
	}
	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}
	
	@Column(name = "CONSULTING_TYPE")
	
	public String getConsultingsType() {
		return consultingsType;
	}
	public void setConsultingsType(String consultingsType) {
		this.consultingsType = consultingsType;
	}
	/*@Column(name = "ADDRESS_ID")
	
	public Integer getAddressId() {
		return addressId;
	}
	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}*/
	@Column(name = "ADDRESS1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	@Column(name = "LOCATITY")
	public String getLocatity() {
		return locatity;
	}
	public void setLocatity(String locatity) {
		this.locatity = locatity;
	}
	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}
	public void setState(String state) {
		this.state = state;
	}	
	@Column(name = "CONTACT_NUMBER")
	public String getContactNumber() {
		return contactNumber;
	}
	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}
	
	@Column(name = "MAX_APPOINTMENTS")

	public Integer getMaxAppointments() {
		return maxAppointments;
	}
	public void setMaxAppointments(Integer maxAppointments) {
		this.maxAppointments = maxAppointments;
	}
	@Column(name = "FEE")
	public Integer getFee() {
		return fee;
	}
	public void setFee(Integer fee) {
		this.fee = fee;
	}
	@Column(name = "CONSULTING_FROM_1")
	public String getConsultingsFrom() {
		return consultingsFrom;
	}
	public void setConsultingsFrom(String consultingsFrom) {
		this.consultingsFrom = consultingsFrom;
	}
	@Column(name = "CONSULTING_TO_1")
	public String getConsultingsTo() {
		return consultingsTo;
	}
	public void setConsultingsTo(String consultingsTo) {
		this.consultingsTo = consultingsTo;
	}
	@Column(name = "CONSULTING_DAYS")
	public String getConsultingsDays() {
		return consultingsDays;
	}
	public void setConsultingsDays(String consultingsDays) {
		this.consultingsDays = consultingsDays;
	}
	@Column(name = "RESPONSE_TIME_FROM")
	public String getResponsetimefrom() {
		return responsetimefrom;
	}
	public void setResponsetimefrom(String responsetimefrom) {
		this.responsetimefrom = responsetimefrom;
	}
	@Column(name = "RESPONSE_TIME_TO")
	public String getResponsetimeto() {
		return responsetimeto;
	}
	public void setResponsetimeto(String responsetimeto) {
		this.responsetimeto = responsetimeto;
	}
}
