package com.medrep.app.entity;
//Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
* TArea generated by hbm2java
*/
@Entity
@Table(name = "P_HEALTHTIPS_SOURCE", uniqueConstraints = @UniqueConstraint(columnNames = "ID") )
public class HealthTipSourceEntity implements java.io.Serializable {
	
	private Integer healthtipid;
	
	private String healthtipSourceName;
	private String healthtipSourceUrl;
	private Integer userId;
	private Date createdOn;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", nullable = false)
	public Integer getHealthtipid() {
		return healthtipid;
	}
	public void setHealthtipid(Integer healthtipid) {
		this.healthtipid = healthtipid;
	}
	
	
	@Column(name = "HEALTHTIPS_SOURCE_NAME")
	public String getHealthtipSourceName() {
		return healthtipSourceName;
	}
	public void setHealthtipSourceName(String healthtipSourceName) {
		this.healthtipSourceName = healthtipSourceName;
	}
	
	
	@Column(name = "HEALTHTIPS_SOURCE_URL")
	public String getHealthtipSourceUrl() {
		return healthtipSourceUrl;
	}
	public void setHealthtipSourceUrl(String healthtipSourceUrl) {
		this.healthtipSourceUrl = healthtipSourceUrl;
	}
	
	@Column(name = "CREATED_BY")
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	@Column(name = "CREATED_ON")
	public Date getCreatedOn() {
		return createdOn;
	}
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}	
}
