package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TLocation generated by hbm2java
 */
@Entity
@Table(name = "T_LOCATION", uniqueConstraints = @UniqueConstraint(columnNames = "USER_ID") )//,@UniqueConstraint(columnNames = "PATIENT_ID"),@UniqueConstraint(columnNames = "DOCTOR_ID")}
public class LocationEntity implements java.io.Serializable {

	private Integer locationId;
	private String address1;
	private String address2;
	private String locatity;
	private String city;
	private String state;
	private String country;
	private String zipcode;
	private String type;
	private UserEntity user;
	private String locationType;
	private Integer doctorId;
	private Integer patientId;

	public LocationEntity() {
	}

	public LocationEntity(String address1, String address2,String locatity, String city, String state, String country, String zipcode,
			String type, Integer userId, String locationType) {
		this.address1 = address1;
		this.address2 = address2;
		this.locatity=locatity;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipcode = zipcode;
		this.type = type;
		this.locationType=locationType;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOCATION_ID", nullable = false)
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "ADDRESS1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	@Column(name = "LOCATITY")
	public String getLocatity() {
		return locatity;
	}
	public void setLocatity(String locatity) {
		this.locatity = locatity;
	}
	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ZIPCODE")
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@ManyToOne
	@JoinColumn(name="USER_ID")
	public UserEntity getUser() {
		return this.user;
	}

	public void setUser(UserEntity user) {
		this.user = user;
	}
	
	@Column(name = "locationtype")
	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	@Column(name = "DOCTOR_ID")
	public Integer getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}
	@Column(name = "PATIENT_ID")

	public Integer getPatientId() {
		return patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}
	

}
