package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TNotificationDetails generated by hbm2java
 */
@Entity
@Table(name = "T_NOTIFICATION_DETAILS", uniqueConstraints = @UniqueConstraint(columnNames = "NOTIFICATION_ID") )
public class NotificationDetailsEntity implements java.io.Serializable {

	private Integer detailId;
	private NotificationEntity notificationEntity;
	private String detailTitle;
	private String detailDesc;

	private String contentType;
	private Integer contentSeq;
	private String contentLocation;
	private String contentName;

	public NotificationDetailsEntity() {
	}

	public NotificationDetailsEntity(String contentType, Integer contentSeq, String contentLocation,
			String contentName) {
		
		this.contentType = contentType;
		this.contentSeq = contentSeq;
		this.contentLocation = contentLocation;
		this.contentName = contentName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DETAIL_ID", nullable = false)
	public Integer getDetailId() {
		return this.detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	@Column(name = "CONTENT_TYPE")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "CONTENT_SEQ")
	public Integer getContentSeq() {
		return this.contentSeq;
	}

	public void setContentSeq(Integer contentSeq) {
		this.contentSeq = contentSeq;
	}

	@Column(name = "CONTENT_LOCATION")
	public String getContentLocation() {
		return this.contentLocation;
	}

	public void setContentLocation(String contentLocation) {
		this.contentLocation = contentLocation;
	}

	@Column(name = "CONTENT_NAME")
	public String getContentName() {
		return this.contentName;
	}

	public void setContentName(String contentName) {
		this.contentName = contentName;
	}
	
	
	@ManyToOne
    @JoinColumn(name="NOTIFICATION_ID",nullable=false)
	public NotificationEntity getNotificationEntity() {
		return notificationEntity;
	}

	public void setNotificationEntity(NotificationEntity notificationEntity) {
		this.notificationEntity = notificationEntity;
	}
	
	@Column(name = "DETAIL_TITLE")
	public String getDetailTitle() {
		return detailTitle;
	}

	public void setDetailTitle(String detailTitle) {
		this.detailTitle = detailTitle;
	}
	
	@Column(name = "DETAIL_DESC")
	public String getDetailDesc() {
		return detailDesc;
	}

	public void setDetailDesc(String detailDesc) {
		this.detailDesc = detailDesc;
	}

}
