package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * TPharmaRep generated by hbm2java
 */
@Entity
@Table(name = "T_PHARMA_REP", uniqueConstraints = @UniqueConstraint(columnNames = "USER_ID"))
public class PharmaRepEntity implements java.io.Serializable {

	private Integer repId;
	private Integer companyId;
	private String coveredArea;
	private Integer managerId;
	private UserEntity user;
	private String coveredZone;
	private String therapeuticId;
	private String status;
	private String managerEmail;
	
	
	@Column(name="MANAGER_EMAIL")
	public String getManagerEmail() {
		return managerEmail;
	}

	public void setManagerEmail(String managerEmail) {
		this.managerEmail = managerEmail;
	}

	public PharmaRepEntity() {
	}

	public PharmaRepEntity(Integer companyId, String coveredArea, Integer managerId, String coveredZone) {
		this.companyId = companyId;
		this.coveredArea = coveredArea;
		this.managerId = managerId;
		this.coveredZone = coveredZone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REP_ID", nullable = false)
	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	@Column(name = "COMPANY_ID", unique = true)
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "COVERED_AREA")
	public String getCoveredArea() {
		return this.coveredArea;
	}

	public void setCoveredArea(String coveredArea) {
		this.coveredArea = coveredArea;
	}

	@Column(name = "MANAGER_ID", unique = true)
	public Integer getManagerId() {
		return this.managerId;
	}

	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	@Column(name = "COVERED_ZONE")
	public String getCoveredZone() {
		return this.coveredZone;
	}

	public void setCoveredZone(String coveredZone) {
		this.coveredZone = coveredZone;
	}
	
	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
	@NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name="USER_ID",nullable=false,unique=true)
	public UserEntity getUser() {
		return user;
	}

	public void setUser(UserEntity user) {
		this.user = user;
	}
	
	@Column(name = "THERAPEUTIC_ID")
	public String getTherapeuticId() {
		return this.therapeuticId;
	}

	public void setTherapeuticId(String therapeuticId) {
		this.therapeuticId = therapeuticId;
	}
	
	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
