package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TPharmaTherapeuticsId generated by hbm2java
 */
@Embeddable
public class PharmaTherapeuticsIdEntity implements java.io.Serializable {

	private int therapeuticId;
	private int companyId;

	public PharmaTherapeuticsIdEntity() {
	}

	public PharmaTherapeuticsIdEntity(int therapeuticId, int companyId) {
		this.therapeuticId = therapeuticId;
		this.companyId = companyId;
	}

	@Column(name = "THERAPEUTIC_ID", nullable = false)
	public int getTherapeuticId() {
		return this.therapeuticId;
	}

	public void setTherapeuticId(int therapeuticId) {
		this.therapeuticId = therapeuticId;
	}

	@Column(name = "COMPANY_ID", unique = true, nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmaTherapeuticsIdEntity))
			return false;
		PharmaTherapeuticsIdEntity castOther = (PharmaTherapeuticsIdEntity) other;

		return (this.getTherapeuticId() == castOther.getTherapeuticId())
				&& (this.getCompanyId() == castOther.getCompanyId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getTherapeuticId();
		result = 37 * result + this.getCompanyId();
		return result;
	}

}
