package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDoctorNotification generated by hbm2java
 */
@Entity
@Table(name = "T_PHARMAREP_NOTIFICATION", uniqueConstraints = { @UniqueConstraint(columnNames = "PHARMAREP_ID"),
		@UniqueConstraint(columnNames = "NOTIFICATION_ID") })
public class PharmaRepNotificationEntity implements java.io.Serializable {

	private Integer userNotificationId;
	private NotificationEntity notificationEntity;
	private Integer pharmaRepId;
	private Integer therapeuticId;
	private Integer companyId;
	private String viewStatus;
	private Date createdOn;
	private Boolean favourite;
	private String feedback;
	private Date viewedOn;

	public PharmaRepNotificationEntity() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_NOTIFICATION_ID", nullable = false)
	public Integer getUserNotificationId() {
		return this.userNotificationId;
	}

	public void setUserNotificationId(Integer userNotificationId) {
		this.userNotificationId = userNotificationId;
	}


	@Column(name = "PHARMAREP_ID")
	public Integer getPharmaRepId() {
		return pharmaRepId;
	}

	public void setPharmaRepId(Integer pharmaRepId) {
		this.pharmaRepId = pharmaRepId;
	}

	@Column(name = "THERAPEUTIC_ID")
	public Integer getTherapeuticId() {
		return this.therapeuticId;
	}

	public void setTherapeuticId(Integer therapeuticId) {
		this.therapeuticId = therapeuticId;
	}

	@Column(name = "COMPANY_ID")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "VIEW_STATUS")
	public String getViewStatus() {
		return this.viewStatus;
	}

	public void setViewStatus(String viewStatus) {
		this.viewStatus = viewStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_ON", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "FAVOURITE")
	public Boolean getFavourite() {
		return this.favourite;
	}

	public void setFavourite(Boolean favourite) {
		this.favourite = favourite;
	}

	@Column(name = "FEEDBACK")
	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VIEWED_ON", length = 19)
	public Date getViewedOn() {
		return this.viewedOn;
	}

	public void setViewedOn(Date viewedOn) {
		this.viewedOn = viewedOn;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.LAZY)
    @JoinColumn(name="NOTIFICATION_ID",nullable=false,unique=true)
	public NotificationEntity getNotificationEntity() {
		return notificationEntity;
	}

	public void setNotificationEntity(NotificationEntity notificationEntity) {
		this.notificationEntity = notificationEntity;
	}

}
