package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TPharmaTherapeutics generated by hbm2java
 */
@Entity
@Table(name = "T_PHARMA_THERAPEUTICS", uniqueConstraints = @UniqueConstraint(columnNames = "COMPANY_ID") )
public class PharmaTherapeuticsEntity implements java.io.Serializable {

	private PharmaTherapeuticsIdEntity id;

	public PharmaTherapeuticsEntity() {
	}

	public PharmaTherapeuticsEntity(PharmaTherapeuticsIdEntity id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "therapeuticId", column = @Column(name = "THERAPEUTIC_ID", nullable = false) ),
			@AttributeOverride(name = "companyId", column = @Column(name = "COMPANY_ID", unique = true, nullable = false) ) })
	public PharmaTherapeuticsIdEntity getId() {
		return this.id;
	}

	public void setId(PharmaTherapeuticsIdEntity id) {
		this.id = id;
	}

}
