package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRepAppointment generated by hbm2java
 */
@Entity
@Table(name = "T_REP_APPOINTMENT")
public class RepAppointmentEntity implements java.io.Serializable {

	private Integer repAppointmentId;
	private Integer appointmentId;
	private Integer repId;
	private Integer doctorId;
	private Date createdOn;
	private String status;

	public RepAppointmentEntity() {
	}

	public RepAppointmentEntity(Integer appointmentId, Integer repId, Integer doctorId, Date createdOn, String status) {
		this.appointmentId = appointmentId;
		this.repId = repId;
		this.doctorId = doctorId;
		this.createdOn = createdOn;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REP_APPOINTMENT_ID", nullable = false)
	public Integer getRepAppointmentId() {
		return this.repAppointmentId;
	}

	public void setRepAppointmentId(Integer repAppointmentId) {
		this.repAppointmentId = repAppointmentId;
	}

	@Column(name = "APPOINTMENT_ID")
	public Integer getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(Integer appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "REP_ID")
	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	@Column(name = "DOCTOR_ID")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_ON")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	
	@Column(name = "STATUS", length = 19)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
