package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Collection;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSurvey generated by hbm2java
 */
@Entity
@Table(name = "T_SURVEY")
public class SurveyEntity implements java.io.Serializable {

	private Integer surveyId;
	private String surveyTitle;
	private String surveyDescription;
	private String surveyUrl;
	private String createdOn;
	private String status;
	private String scheduledStart;
	private String scheduledFinish;
	private Integer companyId;
	private Integer therapeuticId;
	private String  refId;
	private String pushNotification;

	private Collection<DoctorSurveyEntity> doctorSurveys;
	private Collection<PharmaSurveyEntity> repSurveys;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SURVEY_ID", nullable = false)
	public Integer getSurveyId() {
		return this.surveyId;
	}

	@Column(name = "SURVEY_TITLE")
	public String getSurveyTitle() {
		return this.surveyTitle;
	}

	@Column(name = "SURVEY_URL")
	public String getSurveyUrl() {
		return this.surveyUrl;
	}

	@Column(name = "CREATED_ON")
	public String getCreatedOn() {
		return this.createdOn;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return this.status;
	}

	@Column(name = "SCHEDULED_START", length = 19)
	public String getScheduledStart() {
		return this.scheduledStart;
	}

	@Column(name = "SCHEDULED_FINISH")
	public String getScheduledFinish() {
		return this.scheduledFinish;
	}

	@Column(name = "COMPANY_ID")
	public Integer getCompanyId() {
		return this.companyId;
	}

	@Column(name = "THERAPEUTIC_ID")
	public Integer getTherapeuticId() {
		return this.therapeuticId;
	}

	@Column(name = "SURVEY_DESC")
	public String getSurveyDescription() {
		return surveyDescription;
	}

	@Column(name = "REF_ID")
	public String getRefId() {
		return refId;
	}

	@Column(name = "PUSH_STATUS")
	public String getPushNotification() {
		return pushNotification;
	}

	@OneToMany(mappedBy="survey", cascade=CascadeType.ALL, fetch=FetchType.LAZY)
	public Collection<DoctorSurveyEntity> getDoctorSurveys() {
		return doctorSurveys;
	}


	public void setDoctorSurveys(Collection<DoctorSurveyEntity> doctorSurveys) {
		this.doctorSurveys = doctorSurveys;
	}
	
	@OneToMany(mappedBy="survey", cascade=CascadeType.REMOVE, fetch=FetchType.LAZY)
	public Collection<PharmaSurveyEntity> getRepSurveys() {
		return repSurveys;
	}

	public void setRepSurveys(Collection<PharmaSurveyEntity> repSurveys) {
		this.repSurveys = repSurveys;
	}

	public void setPushNotification(String pushNotification) {
		this.pushNotification = pushNotification;
	}

	public void setSurveyDescription(String surveyDescription) {
		this.surveyDescription = surveyDescription;
	}
	public void setTherapeuticId(Integer therapeuticId) {
		this.therapeuticId = therapeuticId;
	}
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public void setScheduledStart(String scheduledStart) {
		this.scheduledStart = scheduledStart;
	}
	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}
	public void setSurveyTitle(String surveyTitle) {
		this.surveyTitle = surveyTitle;
	}

	public void setSurveyUrl(String surveyUrl) {
		this.surveyUrl = surveyUrl;
	}
	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}
	public void setStatus(String status) {
		this.status = status;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}

	public void setScheduledFinish(String scheduledFinish) {
		this.scheduledFinish = scheduledFinish;
	}

	public SurveyEntity() {
	}

	public SurveyEntity(String surveyTitle, String surveyUrl, String createdOn, String status, String scheduledStart,
			String scheduledFinish, Integer companyId, Integer therapeuticId) {
		this.surveyTitle = surveyTitle;
		this.surveyUrl = surveyUrl;
		this.createdOn = createdOn;
		this.status = status;
		this.scheduledStart = scheduledStart;
		this.scheduledFinish = scheduledFinish;
		this.companyId = companyId;
		this.therapeuticId = therapeuticId;
	}	
}