package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MTherapeuticArea generated by hbm2java
 */
@Entity
@Table(name = "M_THERAPEUTIC_AREA")
public class TherapeuticAreaEntity implements java.io.Serializable {

	private Integer therapeuticId;
	private String therapeuticName;
	private String therapeuticDesc;

	public TherapeuticAreaEntity() {
	}

	public TherapeuticAreaEntity(String therapeuticName, String therapeuticDesc) {
		this.therapeuticName = therapeuticName;
		this.therapeuticDesc = therapeuticDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "THERAPEUTIC_ID", nullable = false)
	public Integer getTherapeuticId() {
		return this.therapeuticId;
	}

	public void setTherapeuticId(Integer therapeuticId) {
		this.therapeuticId = therapeuticId;
	}

	@Column(name = "THERAPEUTIC_NAME")
	public String getTherapeuticName() {
		return this.therapeuticName;
	}

	public void setTherapeuticName(String therapeuticName) {
		this.therapeuticName = therapeuticName;
	}

	@Column(name = "THERAPEUTIC_DESC")
	public String getTherapeuticDesc() {
		return this.therapeuticDesc;
	}

	public void setTherapeuticDesc(String therapeuticDesc) {
		this.therapeuticDesc = therapeuticDesc;
	}

}
