package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TArea generated by hbm2java
 */
@Entity
@Table(name = "T_TRANSFORM_SOURCE", uniqueConstraints = @UniqueConstraint(columnNames = "ID") )
public class TransformSourceEntity implements java.io.Serializable {
	
	private Integer transformId;
	private String transformSourceName;
	private String transformSourceUrl;
	private Integer userId;
	private Date createdOn;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", nullable = false)
	public Integer getTransformId() {
		return transformId;
	}
	public void setTransformId(Integer transformId) {
		this.transformId = transformId;
	}
	
	@Column(name = "TRANSAFORM_SOURCE_NAME")
	public String getTransformSourceName() {
		return transformSourceName;
	}
	
	public void setTransformSourceName(String transformSourceName) {
		this.transformSourceName = transformSourceName;
	}
	
	@Column(name = "TRANSAFORM_SOURCE_URL")
	public String getTransformSourceUrl() {
		return transformSourceUrl;
	}
	
	public void setTransformSourceUrl(String transformSourceUrl) {
		this.transformSourceUrl = transformSourceUrl;
	}
	
	@Column(name = "CREATED_BY")
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	@Column(name = "CREATED_ON")
	public Date getCreatedOn() {
		return createdOn;
	}
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}	
}
