package com.medrep.app.entity;
// Generated Aug 2, 2015 5:40:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TZone generated by hbm2java
 */
@Entity
@Table(name = "T_ZONE", uniqueConstraints = @UniqueConstraint(columnNames = "COMPANY_ID") )
public class ZoneEntity implements java.io.Serializable {

	private int zoneId;
	private String zoneName;
	private String zoneDescrption;
	private Integer companyId;
	private Integer zoneOwner;

	public ZoneEntity() {
	}

	public ZoneEntity(int zoneId) {
		this.zoneId = zoneId;
	}

	public ZoneEntity(int zoneId, String zoneName, String zoneDescrption, Integer companyId, Integer zoneOwner) {
		this.zoneId = zoneId;
		this.zoneName = zoneName;
		this.zoneDescrption = zoneDescrption;
		this.companyId = companyId;
		this.zoneOwner = zoneOwner;
	}

	@Id

	@Column(name = "ZONE_ID", nullable = false)
	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	@Column(name = "ZONE_NAME")
	public String getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	@Column(name = "ZONE_DESCRPTION")
	public String getZoneDescrption() {
		return this.zoneDescrption;
	}

	public void setZoneDescrption(String zoneDescrption) {
		this.zoneDescrption = zoneDescrption;
	}

	@Column(name = "COMPANY_ID", unique = true)
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "ZONE_OWNER")
	public Integer getZoneOwner() {
		return this.zoneOwner;
	}

	public void setZoneOwner(Integer zoneOwner) {
		this.zoneOwner = zoneOwner;
	}

}
